# Generated by Django 4.1.7 on 2023-03-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_usertype_userprofile_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='prefLocation',
            field=models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('central', 'Central')], max_length=30),
        ),
    ]
