# Generated by Django 4.1.7 on 2023-03-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_alter_userprofile_preflocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='prefLocation',
            field=models.CharField(max_length=30),
        ),
    ]
