# Generated by Django 4.1.7 on 2023-03-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_alter_userprofile_preflocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userId',
            new_name='user',
        ),
    ]
