# Generated by Django 4.1.7 on 2023-03-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_alter_userprofile_preflocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='N', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefLocation',
            field=models.CharField(choices=[('', '---------'), ('1', 'North'), ('2', 'South'), ('3', 'East'), ('4', 'West'), ('5', 'Central')], max_length=30),
        ),
    ]
