# Generated by Django 4.1.7 on 2023-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_userprofile_gender_alter_userprofile_preflocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='prefLocation',
            field=models.CharField(choices=[('1', 'North'), ('2', 'South'), ('3', 'East'), ('4', 'West'), ('5', 'Central')], max_length=30),
        ),
    ]
