# Generated by Django 4.1.7 on 2023-04-15 10:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0011_businessprofile_isverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=50)),
                ('categoryName', models.CharField(max_length=30)),
                ('dietary_restrictions', multiselectfield.db.fields.MultiSelectField(choices=[('vegetarian', 'Vegetarian'), ('halal', 'Halal'), ('seafood_free', 'Seafood-Free')], max_length=29, validators=[django.core.validators.MaxValueValidator(3)])),
                ('foodCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Homepage.foodcategory')),
            ],
        ),
    ]
