# Generated by Django 4.1.7 on 2023-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0012_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
