# Generated by Django 4.1.7 on 2023-04-15 11:59

import django.core.validators
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0015_alter_food_dietary_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='dietary_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('halal', 'Halal'), ('seafood_free', 'Seafood-Free')], max_length=29, null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
