# Generated by Django 4.1.7 on 2023-04-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0018_userprofile_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
