# Generated by Django 4.1.7 on 2023-04-21 14:54

import django.core.validators
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0019_remove_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dietary_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('halal', 'Halal'), ('seafood_free', 'Seafood-Free')], max_length=29, null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
